// ═══════════════════════════════════════════════════════════════
// DATA MBTI — 60 pertanyaan + profil lengkap 16 tipe
// k: +1 = setuju mengarah ke huruf PERTAMA (E/S/T/J)
// k: -1 = setuju mengarah ke huruf KEDUA (I/N/F/P)
// ═══════════════════════════════════════════════════════════════

const MBTI_QUESTIONS = [
  // ── E / I (15 soal) ──
  { t: "Saya merasa berenergi setelah menghabiskan waktu bersama banyak orang.", d: "EI", k: 1 },
  { t: "Saya lebih suka memikirkan sesuatu matang-matang sebelum mengucapkannya.", d: "EI", k: -1 },
  { t: "Di acara sosial, saya mudah memulai percakapan dengan orang yang belum saya kenal.", d: "EI", k: 1 },
  { t: "Saya butuh waktu sendirian untuk memulihkan energi setelah hari yang ramai.", d: "EI", k: -1 },
  { t: "Saya cenderung berpikir sambil berbicara — ide mengalir saat saya mengucapkannya.", d: "EI", k: 1 },
  { t: "Lingkaran pertemanan saya kecil tetapi sangat dekat.", d: "EI", k: -1 },
  { t: "Saya lebih memilih bekerja dalam tim yang ramai daripada bekerja sendirian.", d: "EI", k: 1 },
  { t: "Telepon mendadak dari orang yang tidak saya kenal terasa melelahkan.", d: "EI", k: -1 },
  { t: "Saya sering menjadi orang yang menghidupkan suasana.", d: "EI", k: 1 },
  { t: "Di kegiatan baru, saya lebih nyaman mengamati dulu sebelum ikut terlibat.", d: "EI", k: -1 },
  { t: "Semakin banyak berinteraksi dengan orang, semakin bersemangat saya.", d: "EI", k: 1 },
  { t: "Menghabiskan akhir pekan sendirian di rumah terdengar menyenangkan bagi saya.", d: "EI", k: -1 },
  { t: "Saya mudah bercerita tentang diri saya kepada orang yang baru dikenal.", d: "EI", k: 1 },
  { t: "Setelah rapat panjang, saya butuh jeda tenang sebelum aktivitas berikutnya.", d: "EI", k: -1 },
  { t: "Saya lebih suka menyampaikan ide secara lisan daripada tertulis.", d: "EI", k: 1 },

  // ── S / N (15 soal) ──
  { t: "Saya lebih percaya pada pengalaman nyata daripada teori.", d: "SN", k: 1 },
  { t: "Saya lebih sering memikirkan berbagai kemungkinan masa depan daripada keadaan saat ini.", d: "SN", k: -1 },
  { t: "Saya memperhatikan detail kecil yang sering dilewatkan orang lain.", d: "SN", k: 1 },
  { t: "Saya menikmati membicarakan konsep abstrak dan ide-ide besar.", d: "SN", k: -1 },
  { t: "Instruksi yang jelas dan langkah demi langkah membuat saya nyaman.", d: "SN", k: 1 },
  { t: "Saya cepat menangkap pola dan makna tersembunyi di balik informasi.", d: "SN", k: -1 },
  { t: "Saya lebih suka menyelesaikan masalah dengan cara yang sudah terbukti berhasil.", d: "SN", k: 1 },
  { t: "Rutinitas yang sama setiap hari membuat saya cepat bosan.", d: "SN", k: -1 },
  { t: "Ketika mengingat kejadian, saya mengingat fakta dan detailnya dengan akurat.", d: "SN", k: 1 },
  { t: "Saya sering melamun atau berimajinasi tentang hal-hal yang belum ada.", d: "SN", k: -1 },
  { t: "Saya menilai ide baru dari kepraktisannya, bukan dari keunikannya.", d: "SN", k: 1 },
  { t: "Saya suka memulai proyek baru meskipun proyek lama belum selesai.", d: "SN", k: -1 },
  { t: "Bagi saya, \"yang penting berjalan\" lebih utama daripada \"yang penting inovatif\".", d: "SN", k: 1 },
  { t: "Saya lebih tertarik pada \"apa yang mungkin terjadi\" daripada \"apa yang sedang terjadi\".", d: "SN", k: -1 },
  { t: "Saya lebih suka petunjuk konkret daripada gambaran umum.", d: "SN", k: 1 },

  // ── T / F (15 soal) ──
  { t: "Saat mengambil keputusan, logika lebih penting daripada perasaan orang.", d: "TF", k: 1 },
  { t: "Saya mudah merasakan suasana hati orang lain.", d: "TF", k: -1 },
  { t: "Kritik yang jujur lebih berharga daripada kata-kata yang menenangkan.", d: "TF", k: 1 },
  { t: "Saya berusaha keras menjaga keharmonisan dalam kelompok.", d: "TF", k: -1 },
  { t: "Saya nyaman berdebat untuk menguji kebenaran sebuah ide.", d: "TF", k: 1 },
  { t: "Keputusan saya sering dipengaruhi oleh dampaknya terhadap orang lain.", d: "TF", k: -1 },
  { t: "Orang menilai saya objektif dan tidak mudah terbawa emosi.", d: "TF", k: 1 },
  { t: "Saya lebih dulu berempati sebelum menganalisis masalah orang lain.", d: "TF", k: -1 },
  { t: "Keadilan berarti memperlakukan semua orang dengan aturan yang sama.", d: "TF", k: 1 },
  { t: "Saya sulit menyampaikan keputusan yang akan menyakiti perasaan orang.", d: "TF", k: -1 },
  { t: "Dalam diskusi, saya fokus pada kelemahan argumen, bukan pada perasaan pembicaranya.", d: "TF", k: 1 },
  { t: "Pujian dan apresiasi sangat penting bagi semangat kerja saya.", d: "TF", k: -1 },
  { t: "Saya lebih memilih benar daripada disukai.", d: "TF", k: 1 },
  { t: "Saya sering mengalah demi menjaga hubungan baik.", d: "TF", k: -1 },
  { t: "Efisiensi lebih penting daripada kenyamanan perasaan semua pihak.", d: "TF", k: 1 },

  // ── J / P (15 soal) ──
  { t: "Saya merasa tenang ketika semuanya sudah terjadwal dan terencana.", d: "JP", k: 1 },
  { t: "Saya suka membiarkan pilihan tetap terbuka selama mungkin.", d: "JP", k: -1 },
  { t: "Saya menyelesaikan tugas jauh sebelum tenggat waktu.", d: "JP", k: 1 },
  { t: "Saya justru bekerja paling baik dalam dorongan menit-menit terakhir.", d: "JP", k: -1 },
  { t: "Daftar tugas (to-do list) adalah sahabat saya.", d: "JP", k: 1 },
  { t: "Rencana yang berubah mendadak justru terasa menyegarkan.", d: "JP", k: -1 },
  { t: "Meja kerja dan file saya tertata rapi.", d: "JP", k: 1 },
  { t: "Saya sering memulai banyak hal sekaligus tanpa menyelesaikan semuanya.", d: "JP", k: -1 },
  { t: "Keputusan yang sudah dibuat sebaiknya tidak diubah-ubah lagi.", d: "JP", k: 1 },
  { t: "Saya lebih suka beradaptasi mengikuti situasi daripada terpaku pada rencana.", d: "JP", k: -1 },
  { t: "Liburan tanpa itinerary membuat saya gelisah.", d: "JP", k: 1 },
  { t: "Aturan bagi saya lebih seperti saran daripada kewajiban.", d: "JP", k: -1 },
  { t: "Saya menyukai kejelasan: kapan, di mana, siapa, dan bagaimana.", d: "JP", k: 1 },
  { t: "Spontanitas membuat hidup lebih menarik daripada keteraturan.", d: "JP", k: -1 },
  { t: "Menunda pekerjaan membuat saya sangat tidak nyaman.", d: "JP", k: 1 },
];

// Nama fungsi kognitif
const FUNGSI_KOGNITIF = {
  Se: ["Se — Pengindraan Ekstrover", "Hidup di saat ini; peka terhadap fakta, sensasi, dan peluang konkret di sekitarnya."],
  Si: ["Si — Pengindraan Introver", "Membandingkan situasi dengan pengalaman & data masa lalu; kekuatan pada memori detail dan konsistensi."],
  Ne: ["Ne — Intuisi Ekstrover", "Melihat banyak kemungkinan sekaligus; menghubungkan ide-ide yang tampak tak berhubungan."],
  Ni: ["Ni — Intuisi Introver", "Menyaring pola menjadi satu visi jangka panjang; \"tiba-tiba paham\" arah ke depan."],
  Te: ["Te — Pemikiran Ekstrover", "Mengorganisir dunia luar: sistem, target, efisiensi, dan keputusan cepat berbasis logika objektif."],
  Ti: ["Ti — Pemikiran Introver", "Membangun kerangka logika internal yang presisi; menganalisis sampai ke akar konsep."],
  Fe: ["Fe — Perasaan Ekstrover", "Membaca dan menjaga harmoni kelompok; peka terhadap kebutuhan emosional orang lain."],
  Fi: ["Fi — Perasaan Introver", "Kompas nilai pribadi yang dalam; keputusan diukur dari keselarasan dengan prinsip diri."],
};

// Kelompok 16personalities-style
const MBTI_GROUPS = {
  Analis:     { warna: "#7c5cbf", desc: "Rasional, mandiri, haus kompetensi. Kuat dalam strategi & sistem." },
  Diplomat:   { warna: "#2e9e6b", desc: "Empatik, idealis, berorientasi makna. Kuat dalam hubungan & inspirasi." },
  Sentinel:   { warna: "#3a7bd5", desc: "Praktis, teratur, dapat diandalkan. Kuat dalam stabilitas & eksekusi." },
  Penjelajah: { warna: "#d5a53a", desc: "Spontan, adaptif, cakap secara praktis. Kuat dalam improvisasi & aksi." },
};

// Profil lengkap 16 tipe. pct = perkiraan proporsi populasi (data AS, Myers & Briggs Foundation)
const MBTI_TYPES = {
  ISTJ: {
    nick: "Ahli Logistik", grup: "Sentinel", pct: 11.6,
    tagline: "Praktis, faktual, dan dapat diandalkan tanpa banyak kata.",
    desc: "ISTJ adalah tulang punggung organisasi: teliti, bertanggung jawab, dan setia pada komitmen. Mereka bekerja sistematis berdasarkan fakta dan pengalaman, jarang membuat janji yang tidak bisa ditepati. Perubahan diterima jika memang terbukti lebih baik — bukan karena sekadar tren.",
    fungsi: ["Si", "Te", "Fi", "Ne"],
    kekuatan: ["Sangat bertanggung jawab & konsisten", "Teliti dan berorientasi fakta", "Tenang di bawah tekanan", "Menepati tenggat & prosedur", "Loyal pada organisasi", "Praktis dan hemat sumber daya"],
    kelemahan: ["Kaku terhadap perubahan mendadak", "Sulit mengekspresikan perasaan", "Bisa terlalu berpegang pada aturan", "Menghakimi cara kerja yang berbeda", "Kadang memikul beban sendirian"],
    kerja: "Unggul di lingkungan terstruktur dengan tanggung jawab jelas dan standar terukur. Berikan prosedur, wewenang, dan waktu — pekerjaan akan selesai dengan kualitas stabil.",
    komunikasi: "Bicara seperlunya, faktual, dan to the point. Saat berkomunikasi dengannya, siapkan data dan kronologi yang jelas; hindari ide yang masih mengambang.",
    karier: ["Akuntan / Auditor", "Manajer Operasional", "Analis Keuangan", "Pegawai Negeri / Administrasi Publik", "Perwira Militer / Polisi", "Manajer Logistik & Supply Chain", "Quality Control / QA", "Inspektur / Compliance Officer", "Apoteker", "Manajer Proyek Konstruksi"],
    tokoh: ["Angela Merkel", "Jeff Bezos", "George Washington", "Natalie Portman"],
    tips: ["Latih fleksibilitas: coba satu cara baru kecil setiap bulan.", "Ungkapkan apresiasi kepada rekan secara verbal — bagi orang lain itu penting.", "Delegasikan; tidak semua harus Anda kerjakan sendiri agar 'benar'."],
  },
  ISFJ: {
    nick: "Pembela", grup: "Sentinel", pct: 13.8,
    tagline: "Pelindung yang hangat, teliti, dan selalu siap membantu.",
    desc: "ISFJ menggabungkan kepedulian tulus dengan ketelitian praktis. Mereka mengingat detail tentang orang-orang di sekitarnya dan bekerja keras di balik layar demi kenyamanan bersama. Sering kali kontribusinya besar tetapi jarang menonjolkan diri.",
    fungsi: ["Si", "Fe", "Ti", "Ne"],
    kekuatan: ["Suportif dan dapat diandalkan", "Sangat teliti & bermemori detail kuat", "Sabar dan tekun", "Loyal pada orang dan organisasi", "Praktis dalam membantu", "Peka terhadap kebutuhan orang lain"],
    kelemahan: ["Sulit berkata 'tidak' (rawan kelelahan)", "Memendam perasaan sendiri", "Terlalu merendah, jarang menuntut haknya", "Menghindari konflik yang perlu", "Sulit menerima perubahan besar"],
    kerja: "Bersinar di peran pelayanan dan dukungan yang menuntut ketelitian dan empati. Berikan apresiasi eksplisit — mereka jarang memintanya tetapi sangat membutuhkannya.",
    komunikasi: "Lembut, sopan, dan mendengarkan dengan sungguh-sungguh. Sampaikan kritik secara privat dan seimbangkan dengan pengakuan atas kontribusinya.",
    karier: ["Perawat / Tenaga Kesehatan", "Guru SD / PAUD", "Staf HR (administrasi & kesejahteraan)", "Pekerja Sosial", "Pustakawan", "Customer Service", "Sekretaris / Asisten Eksekutif", "Ahli Gizi", "Konselor Sekolah", "Administrasi Medis"],
    tokoh: ["Ibu Teresa", "Kate Middleton", "Beyoncé", "Rosa Parks"],
    tips: ["Belajar menolak dengan sopan — energi Anda juga berharga.", "Sampaikan kebutuhan Anda sebelum menumpuk jadi kekecewaan.", "Terima pujian tanpa mengecilkannya."],
  },
  INFJ: {
    nick: "Advokat", grup: "Diplomat", pct: 1.5,
    tagline: "Idealis yang tenang dengan visi mendalam tentang manusia.",
    desc: "INFJ — tipe paling langka — memadukan intuisi tajam tentang manusia dengan komitmen kuat pada nilai. Mereka pendengar yang dalam, mampu melihat potensi orang lain, dan terdorong untuk membuat perubahan bermakna, bukan sekadar sukses materi.",
    fungsi: ["Ni", "Fe", "Ti", "Se"],
    kekuatan: ["Wawasan mendalam tentang orang", "Idealis sekaligus terorganisir", "Penulis/komunikator yang kuat", "Berprinsip dan berintegritas", "Kreatif memecahkan masalah manusia", "Mampu menginspirasi perubahan"],
    kelemahan: ["Perfeksionis dan keras pada diri sendiri", "Mudah lelah secara emosional (burnout)", "Terlalu privat, sulit dibaca", "Sensitif terhadap kritik", "Sulit kompromi pada nilai yang diyakini"],
    kerja: "Terbaik di pekerjaan bermakna yang menyentuh pengembangan manusia. Butuh ketenangan dan otonomi; bising dan politik kantor menguras energinya dengan cepat.",
    komunikasi: "Hangat namun terukur; lebih dalam dalam percakapan satu-satu. Berikan konteks 'mengapa' di balik setiap permintaan — makna adalah bahan bakarnya.",
    karier: ["Konselor / Psikolog", "HRD (pengembangan talenta)", "Penulis / Editor", "Dosen / Pendidik", "Pekerja Sosial / NGO", "Dokter / Psikiater", "Desainer Instruksional", "Coach Pengembangan Diri", "Peneliti Sosial", "Rohaniwan"],
    tokoh: ["Nelson Mandela", "Martin Luther King Jr.", "Lady Gaga", "Carl Jung"],
    tips: ["Tetapkan batas energi — Anda tidak bisa menolong semua orang sekaligus.", "Bagikan proses berpikir Anda; jangan hanya kesimpulannya.", "Terima bahwa 'cukup baik' kadang memang cukup."],
  },
  INTJ: {
    nick: "Arsitek", grup: "Analis", pct: 2.1,
    tagline: "Perancang strategi dengan rencana untuk segala hal.",
    desc: "INTJ adalah pemikir strategis yang mandiri: melihat pola besar, merancang sistem, dan mengeksekusi visi jangka panjang dengan disiplin. Standar mereka sangat tinggi — untuk diri sendiri maupun orang lain — dan mereka menghargai kompetensi di atas segalanya.",
    fungsi: ["Ni", "Te", "Fi", "Se"],
    kekuatan: ["Pemikiran strategis jangka panjang", "Mandiri dan tegas", "Haus pengetahuan", "Objektif dalam keputusan", "Inovatif memperbaiki sistem", "Konsisten mengeksekusi visi"],
    kelemahan: ["Terkesan dingin atau arogan", "Tidak sabar pada inefisiensi & basa-basi", "Mengabaikan faktor emosi", "Terlalu kritis", "Sulit mendelegasikan pada yang dianggap kurang kompeten"],
    kerja: "Unggul di peran analitis dengan otonomi tinggi dan masalah kompleks. Rapat tanpa agenda dan birokrasi berlebihan adalah musuh produktivitasnya.",
    komunikasi: "Langsung, hemat kata, berbasis logika. Datanglah dengan data dan usulan yang sudah dipikirkan; ia menghargai argumen kuat, bahkan yang menentangnya.",
    karier: ["Data Scientist / Analis Data", "Arsitek Sistem / IT", "Insinyur", "Konsultan Strategi / Manajemen", "Ilmuwan / Peneliti", "Dokter Spesialis", "Ekonom", "Pengembang Perangkat Lunak", "Perencana Keuangan / Aktuaris", "Direktur Teknologi (CTO)"],
    tokoh: ["Elon Musk", "Michelle Obama", "Isaac Newton", "Christopher Nolan"],
    tips: ["Sampaikan apresiasi — tim Anda bukan hanya mesin eksekusi.", "Uji visi Anda lebih awal dengan umpan balik orang lain.", "Latih kesabaran menjelaskan; tidak semua orang melompat ke kesimpulan secepat Anda."],
  },
  ISTP: {
    nick: "Virtuoso", grup: "Penjelajah", pct: 5.4,
    tagline: "Pemecah masalah praktis yang tenang dan tangkas.",
    desc: "ISTP adalah 'insinyur alami': tenang, logis, dan paling hidup saat tangannya memecahkan masalah nyata. Mereka belajar dengan mencoba langsung, tetap dingin dalam krisis, dan tidak suka diatur berlebihan.",
    fungsi: ["Ti", "Se", "Ni", "Fe"],
    kekuatan: ["Sangat tenang saat krisis", "Cakap teknis & mekanis", "Efisien — tanpa drama", "Fleksibel dan adaptif", "Berani mengambil tindakan", "Mandiri"],
    kelemahan: ["Mudah bosan pada rutinitas & teori panjang", "Komunikasi minim, sulit ditebak", "Menghindari komitmen jangka panjang", "Kurang peka pada kebutuhan emosional", "Menyimpan masalah sendiri"],
    kerja: "Terbaik di pekerjaan hands-on dengan variasi dan kebebasan teknis. Beri masalah konkret, alat yang tepat, dan ruang — bukan meeting maraton.",
    komunikasi: "Singkat dan fungsional. Tanyakan pendapatnya secara spesifik; jangan paksa small talk. Tunjukkan, jangan hanya jelaskan.",
    karier: ["Teknisi / Insinyur Mesin", "Pilot", "Programmer / DevOps", "Ahli Forensik", "Paramedis / Rescue", "Montir / Teknisi Otomotif", "Operator Alat Berat", "Atlet / Pelatih Fisik", "Elektrisi", "Teknisi Jaringan"],
    tokoh: ["Clint Eastwood", "Bear Grylls", "Michael Jordan", "Erwin Rommel"],
    tips: ["Kabari orang lain tentang progres Anda — diam sering disalahartikan.", "Selesaikan hal membosankan 20% itu; dampaknya besar.", "Latih mengungkapkan apresiasi pada tim."],
  },
  ISFP: {
    nick: "Petualang", grup: "Penjelajah", pct: 8.8,
    tagline: "Seniman yang lembut, spontan, dan setia pada nilai pribadi.",
    desc: "ISFP hidup lewat pengalaman dan estetika: peka terhadap keindahan, hangat secara diam-diam, dan sangat teguh pada nilai pribadinya meski jarang mendebatkannya. Mereka menunjukkan kasih lewat tindakan, bukan kata-kata.",
    fungsi: ["Fi", "Se", "Ni", "Te"],
    kekuatan: ["Kepekaan estetika tinggi", "Hangat dan tidak menghakimi", "Fleksibel dan spontan", "Praktis dalam berkarya", "Setia pada nilai pribadi", "Pengamat yang baik"],
    kelemahan: ["Menghindari konflik dan kritik", "Sulit merencanakan jangka panjang", "Mudah tersinggung namun memendam", "Kurang asertif memperjuangkan diri", "Bisa terlalu impulsif"],
    kerja: "Bersinar di pekerjaan kreatif atau pelayanan langsung yang hasilnya terlihat dan terasa. Butuh suasana kerja yang harmonis dan bebas micromanagement.",
    komunikasi: "Lembut dan pendiam; lebih terbuka lewat karya atau tindakan. Berikan umpan balik dengan hati-hati dan fokus pada karya, bukan pribadinya.",
    karier: ["Desainer Grafis / UI", "Chef / Pastry", "Fotografer / Videografer", "Perawat / Terapis", "Fisioterapis", "Penata Rambut / MUA", "Florist / Penata Interior", "Musisi / Seniman", "Dokter Hewan / Perawat Satwa", "Pengrajin"],
    tokoh: ["Michael Jackson", "Frida Kahlo", "Keanu Reeves", "Audrey Hepburn"],
    tips: ["Latih menyuarakan ketidaksetujuan lebih awal, sebelum menumpuk.", "Buat target kecil berjangka — mimpi butuh jembatan.", "Kritik atas karya ≠ penolakan atas diri Anda."],
  },
  INFP: {
    nick: "Mediator", grup: "Diplomat", pct: 4.4,
    tagline: "Idealis puitis yang digerakkan oleh nilai dan makna.",
    desc: "INFP memandang dunia lewat lensa nilai dan kemungkinan: apa yang bisa lebih baik, lebih adil, lebih bermakna. Mereka kreatif, empatik, dan otentik — pekerjaan tanpa makna akan mematikan semangatnya secepat apa pun gajinya.",
    fungsi: ["Fi", "Ne", "Si", "Te"],
    kekuatan: ["Empati yang dalam", "Kreativitas & imajinasi kuat", "Integritas pada nilai", "Terbuka pada perspektif berbeda", "Kemampuan menulis/berbahasa kuat", "Mampu melihat sisi baik orang"],
    kelemahan: ["Terlalu idealis, mudah kecewa", "Sulit dengan detail administratif rutin", "Menunda karena perfeksionisme", "Terlalu personal menanggapi kritik", "Sulit tegas menghadapi konflik"],
    kerja: "Terbaik dalam pekerjaan misi-driven dengan ruang kreatif dan otonomi. Hubungkan tugas dengan dampaknya bagi manusia — itu bahan bakar utamanya.",
    komunikasi: "Reflektif dan tulus; tidak nyaman dengan konfrontasi keras. Beri waktu berpikir sebelum meminta keputusan; hargai idenya meski belum matang.",
    karier: ["Penulis / Content Writer", "Psikolog / Konselor", "Guru / Dosen Humaniora", "Penerjemah / Interpreter", "Desainer Grafis", "Pekerja NGO / Kemanusiaan", "Pustakawan", "Terapis Seni", "Peneliti Budaya", "Spesialis Branding"],
    tokoh: ["William Shakespeare", "J.R.R. Tolkien", "Princess Diana", "Studio Ghibli — Hayao Miyazaki (sering diasosiasikan)"],
    tips: ["Pecah proyek besar menjadi langkah kecil bertenggat.", "Selesai lebih baik daripada sempurna.", "Pisahkan kritik atas ide dari kritik atas diri Anda."],
  },
  INTP: {
    nick: "Ahli Logika", grup: "Analis", pct: 3.3,
    tagline: "Pemikir inovatif dengan rasa haus tak terpuaskan akan pengetahuan.",
    desc: "INTP hidup di dunia ide: membongkar konsep, menemukan inkonsistensi, dan membangun kerangka teori yang presisi. Mereka orisinal dan objektif, tetapi sering lebih menikmati memecahkan masalah daripada mengimplementasikan solusinya.",
    fungsi: ["Ti", "Ne", "Si", "Fe"],
    kekuatan: ["Analisis logis yang tajam", "Orisinal dan inovatif", "Objektif, terbuka pada bukti baru", "Cepat menguasai konsep kompleks", "Jujur secara intelektual", "Mandiri dalam berpikir"],
    kelemahan: ["Menunda eksekusi & administrasi", "Terjebak analysis paralysis", "Kurang peka pada dinamika emosi", "Sulit dengan aturan yang dianggap tidak logis", "Meninggalkan proyek saat tantangan intelektualnya habis"],
    kerja: "Unggul di riset dan pemecahan masalah kompleks dengan kebebasan eksplorasi. Pasangkan dengan rekan yang kuat eksekusi agar ide sampai ke garis akhir.",
    komunikasi: "Presisi dan penuh nuansa; senang debat ide tanpa menganggapnya konflik pribadi. Jangan tersinggung oleh koreksinya — itu bentuk keterlibatannya.",
    karier: ["Peneliti / Ilmuwan", "Programmer / Software Engineer", "Matematikawan / Statistikus", "Analis Sistem", "Profesor / Akademisi", "Filsuf / Penulis Sains", "Arsitek Data", "Game Designer", "Ekonom Riset", "Insinyur R&D"],
    tokoh: ["Albert Einstein", "Bill Gates", "Marie Curie", "Charles Darwin"],
    tips: ["Tetapkan tenggat eksternal — otak Anda menghormati deadline nyata.", "Sampaikan '80% jadi' daripada menunggu sempurna.", "Luangkan energi untuk relasi kerja; itu juga sistem yang bisa dipelajari."],
  },
  ESTP: {
    nick: "Pengusaha", grup: "Penjelajah", pct: 4.3,
    tagline: "Enerjik, taktis, dan paling hidup di tengah aksi.",
    desc: "ESTP adalah orang lapangan sejati: cepat membaca situasi, berani mengambil risiko terukur, dan pandai bernegosiasi di saat genting. Mereka pragmatis — teori boleh, tapi buktikan di lapangan.",
    fungsi: ["Se", "Ti", "Fe", "Ni"],
    kekuatan: ["Berani dan cepat bertindak", "Persuasif dan karismatik", "Sangat jeli membaca situasi & orang", "Pragmatis memecahkan masalah", "Tahan tekanan tinggi", "Networking alami"],
    kelemahan: ["Tidak sabar pada perencanaan panjang", "Mengambil risiko berlebihan", "Mudah bosan; benci rutinitas", "Kurang memikirkan dampak jangka panjang", "Bisa menabrak aturan & struktur"],
    kerja: "Terbaik di peran dinamis dengan target jelas dan interaksi tinggi. Ukur dengan hasil, bukan jam duduk; beri variasi agar tidak jenuh.",
    komunikasi: "Langsung, enerjik, kadang blak-blakan. Ajak diskusi sambil beraksi; hindari memo panjang — ringkas dan konkret lebih efektif.",
    karier: ["Sales / Business Development", "Wirausaha", "Marketing Lapangan", "Broker / Trader", "Polisi / Penegak Hukum", "Paramedis / Gawat Darurat", "Event Organizer", "Atlet Profesional", "Negosiator", "Manajer Operasional Lapangan"],
    tokoh: ["Donald Trump", "Madonna", "Ernest Hemingway", "Jack Nicholson"],
    tips: ["Sebelum melompat, tanya: apa dampaknya 6 bulan ke depan?", "Selesaikan administrasi kecil hari itu juga — jangan menumpuk.", "Dengarkan sampai selesai sebelum merespons."],
  },
  ESFP: {
    nick: "Penghibur", grup: "Penjelajah", pct: 8.5,
    tagline: "Spontan, hangat, dan membuat hidup terasa seperti pesta.",
    desc: "ESFP membawa energi dan kehangatan ke mana pun mereka pergi. Mereka praktis, murah hati, cepat akrab, dan pandai membuat orang merasa nyaman — perekat sosial alami dalam tim.",
    fungsi: ["Se", "Fi", "Te", "Ni"],
    kekuatan: ["Antusias dan menyenangkan", "Cepat membangun keakraban", "Praktis dan sigap membantu", "Peka estetika & tren", "Fleksibel terhadap perubahan", "Berani tampil"],
    kelemahan: ["Mudah teralihkan; sulit fokus panjang", "Menghindari konflik & topik berat", "Kurang menyukai perencanaan jangka panjang", "Sensitif terhadap kritik", "Impulsif dalam keuangan/keputusan"],
    kerja: "Bersinar di peran yang melibatkan orang, penampilan, dan tempo cepat. Hindari menempatkannya sendirian di balik tumpukan dokumen.",
    komunikasi: "Ramah, ekspresif, dan personal. Sampaikan kritik dengan hangat dan langsung tunjukkan caranya; jangan mempermalukan di depan umum.",
    karier: ["Entertainer / Presenter", "Event Organizer", "Sales & Promosi", "Humas / PR", "Guru TK / PAUD", "Pramugari/a", "Perawat / Bidan", "Desainer Fashion", "Tour Guide", "Customer Experience"],
    tokoh: ["Adele", "Jamie Oliver", "Marilyn Monroe", "Will Smith"],
    tips: ["Gunakan alat bantu fokus (timer, daftar) untuk pekerjaan detail.", "Sisihkan tabungan otomatis sebelum uang 'menguap'.", "Hadapi percakapan sulit — menundanya membuat lebih sulit."],
  },
  ENFP: {
    nick: "Juru Kampanye", grup: "Diplomat", pct: 8.1,
    tagline: "Antusias, kreatif, dan mampu melihat kemungkinan di semua hal.",
    desc: "ENFP memancarkan antusiasme yang menular: penuh ide, mudah terhubung dengan orang, dan melihat potensi di mana pun. Mereka butuh kebebasan dan makna — dua hal yang membuat kreativitasnya menyala.",
    fungsi: ["Ne", "Fi", "Te", "Si"],
    kekuatan: ["Kreativitas & ide tak habis-habis", "Komunikator dan storyteller alami", "Empati tinggi, cepat akrab", "Antusiasme yang menular", "Adaptif terhadap perubahan", "Mampu menghubungkan orang & ide"],
    kelemahan: ["Sulit menyelesaikan yang sudah dimulai", "Mudah bosan pada rutinitas & detail", "Terlalu banyak berkomitmen (overcommit)", "Mudah terluka oleh penolakan", "Kurang disiplin administrasi"],
    kerja: "Terbaik di peran kreatif dan people-oriented dengan variasi tinggi. Pasangkan dengan sistem/rekan yang menjaga detail agar ide besarnya terwujud.",
    komunikasi: "Hangat, ekspresif, penuh cerita. Beri ruang brainstorming sebelum menilai idenya; hubungkan tugas dengan visi yang lebih besar.",
    karier: ["Jurnalis / Penyiar", "Konsultan / Trainer", "Humas / Komunikasi", "Content Creator", "Entrepreneur Kreatif", "Psikolog / Konselor", "Marketing / Brand Strategist", "Pengajar", "Perencana Acara", "Fundraiser NGO"],
    tokoh: ["Robin Williams", "Walt Disney", "Oprah (sering juga disebut ENFJ)", "Robert Downey Jr."],
    tips: ["Batasi proyek aktif maksimal 3 — selesaikan sebelum mulai yang baru.", "Jadwalkan 'jam detail' harian yang singkat tapi rutin.", "Tidak semua orang harus menyukai Anda — dan itu tidak apa-apa."],
  },
  ENTP: {
    nick: "Pendebat", grup: "Analis", pct: 3.2,
    tagline: "Pemikir cepat yang tidak bisa menolak tantangan intelektual.",
    desc: "ENTP adalah generator ide dan penantang status quo: cepat, cerdas, dan menikmati adu argumen sebagai olahraga otak. Mereka melihat celah dan peluang yang dilewatkan orang lain — meski tidak selalu tertarik mengeksekusinya sampai tuntas.",
    fungsi: ["Ne", "Ti", "Fe", "Si"],
    kekuatan: ["Berpikir cepat & orisinal", "Debat dan persuasi ulung", "Berani menantang status quo", "Luas wawasan lintas bidang", "Tangkas beradaptasi", "Melihat peluang lebih dulu"],
    kelemahan: ["Argumentatif — bisa melelahkan orang", "Sulit fokus & menuntaskan", "Meremehkan rutinitas & prosedur", "Kurang peka perasaan saat berdebat", "Menunda keputusan demi opsi baru"],
    kerja: "Unggul dalam inovasi, strategi, dan pemecahan masalah baru. Beri masalah sulit dan lawan diskusi yang setara; hindari mengurungnya dalam prosedur kaku.",
    komunikasi: "Cepat, penuh ide dan tanya-jawab. Jangan artikan debatnya sebagai serangan pribadi; ajak dia menguji ide, bukan sekadar menyetujui.",
    karier: ["Entrepreneur / Founder", "Pengacara", "Konsultan Strategi", "Product Manager", "Marketer / Growth Hacker", "Insinyur Inovasi / R&D", "Politisi / Analis Kebijakan", "Penulis Opini / Komedian", "Venture Capitalist", "Negosiator Bisnis"],
    tokoh: ["Thomas Edison", "Steve Wozniak", "Sacha Baron Cohen", "Mark Twain"],
    tips: ["Pilih 1 ide per kuartal untuk dieksekusi sampai tuntas.", "Sebelum mendebat, tanya diri: apakah ini perlu dimenangkan?", "Hargai orang yang menjaga sistem berjalan — mereka melengkapi Anda."],
  },
  ESTJ: {
    nick: "Eksekutif", grup: "Sentinel", pct: 8.7,
    tagline: "Pengelola andal yang membuat segalanya berjalan tepat waktu.",
    desc: "ESTJ adalah organisator par excellence: tegas, sistematis, dan berorientasi hasil. Mereka menghargai kejelasan, tradisi yang terbukti, dan kerja keras — serta tidak ragu mengambil kendali saat keadaan kacau.",
    fungsi: ["Te", "Si", "Ne", "Fi"],
    kekuatan: ["Kepemimpinan tegas & terstruktur", "Eksekusi dan disiplin kuat", "Jujur dan lugas", "Dapat diandalkan menepati komitmen", "Pengambil keputusan cepat", "Ahli membangun prosedur & ketertiban"],
    kelemahan: ["Kaku pada cara baru yang belum terbukti", "Terlalu blak-blakan; bisa melukai", "Workaholic; menuntut hal sama dari orang lain", "Kurang sabar pada proses emosional", "Sulit mengakui kesalahan"],
    kerja: "Unggul memimpin operasi dengan target, struktur, dan akuntabilitas jelas. Beri wewenang formal dan metrik — hasilnya akan terukur dan tepat waktu.",
    komunikasi: "Lugas, terstruktur, berorientasi tindakan. Sampaikan usulan dengan data dan langkah konkret; jangan bertele-tele.",
    karier: ["Manajer / Direktur Operasional", "Manajer Proyek", "Perwira Militer", "Hakim / Jaksa", "Kepala Sekolah", "Manajer Keuangan", "Administrator Bisnis", "Supervisor Produksi", "Kepala Cabang Bank", "Birokrat Senior"],
    tokoh: ["Sonia Sotomayor", "Henry Ford", "Margaret Thatcher (sering juga disebut ENTJ)", "John D. Rockefeller"],
    tips: ["Dengarkan dulu secara penuh sebelum memutuskan.", "Sisipkan apresiasi dalam setiap koreksi.", "Uji ide baru dalam skala kecil sebelum menolaknya."],
  },
  ESFJ: {
    nick: "Konsul", grup: "Sentinel", pct: 12.3,
    tagline: "Penjaga kebersamaan yang hangat, peduli, dan terorganisir.",
    desc: "ESFJ adalah perekat komunitas: perhatian pada kebutuhan praktis orang lain, pandai mengorganisir acara dan orang, serta menjaga tradisi kebersamaan. Mereka bekerja keras agar semua orang merasa dilibatkan dan dihargai.",
    fungsi: ["Fe", "Si", "Ne", "Ti"],
    kekuatan: ["Sangat peduli dan suportif", "Terorganisir dan praktis", "Loyal dan bertanggung jawab", "Pandai membaca kebutuhan kelompok", "Kolaborator yang andal", "Mahir membangun keakraban tim"],
    kelemahan: ["Terlalu butuh pengakuan & disukai", "Sulit menerima kritik", "Bisa terlalu mencampuri urusan orang", "Kaku pada norma sosial", "Mengorbankan kebutuhan sendiri"],
    kerja: "Bersinar di peran koordinasi dan pelayanan dengan interaksi tinggi. Berikan apresiasi publik dan kejelasan harapan — dua bahan bakar utamanya.",
    komunikasi: "Ramah, kooperatif, dan penuh perhatian. Sampaikan kritik dengan hangat dan privat; libatkan dalam keputusan yang menyangkut tim.",
    karier: ["HR / People Operations", "Guru", "Perawat / Bidan", "Event Coordinator", "Customer Relations", "Manajer Restoran / Hospitality", "Sekretaris Organisasi", "Sales Consultant", "Community Manager", "Administrasi Sekolah/RS"],
    tokoh: ["Taylor Swift", "Jennifer Lopez", "Hugh Jackman", "Steve Harvey"],
    tips: ["Nilai diri Anda tidak ditentukan oleh persetujuan semua orang.", "Latih menerima kritik sebagai data, bukan penolakan.", "Sisakan waktu merawat diri sendiri, bukan hanya orang lain."],
  },
  ENFJ: {
    nick: "Protagonis", grup: "Diplomat", pct: 2.5,
    tagline: "Pemimpin karismatik yang menumbuhkan orang lain.",
    desc: "ENFJ adalah mentor alami: karismatik, empatik, dan terdorong membantu orang lain bertumbuh. Mereka pandai membaca ruangan, menyatukan orang menuju visi bersama, dan berbicara dengan cara yang menggerakkan hati.",
    fungsi: ["Fe", "Ni", "Se", "Ti"],
    kekuatan: ["Kepemimpinan yang menginspirasi", "Empati dan kepekaan sosial tinggi", "Komunikator/orator ulung", "Altruistis dan tulus", "Pandai mengembangkan orang", "Organisator kolaborasi yang baik"],
    kelemahan: ["Terlalu idealis pada orang", "Sulit membuat keputusan yang mengecewakan orang", "Mengabaikan kebutuhan sendiri (rawan burnout)", "Terlalu sensitif pada kritik", "Bisa terkesan terlalu mencampuri"],
    kerja: "Terbaik memimpin tim dan mengembangkan talenta. Beri peran yang menghubungkan orang dengan tujuan; lindungi dari beban emosional berlebih.",
    komunikasi: "Hangat, artikulatif, dan persuasif. Jujurlah padanya dengan lembut — ia menghargai ketulusan lebih dari pujian kosong.",
    karier: ["HRD / Learning & Development", "Coach / Mentor", "Guru / Dosen", "Public Relations", "Pemimpin NGO / Komunitas", "Konselor", "Politisi / Diplomat", "Manajer Tim Sales", "Rohaniwan", "Fasilitator Pelatihan"],
    tokoh: ["Barack Obama", "Oprah Winfrey", "Malala Yousafzai", "Jacinda Ardern"],
    tips: ["Belajar mengecewakan orang demi keputusan yang benar.", "Jadwalkan waktu pemulihan pribadi seketat jadwal membantu orang.", "Tidak semua orang ingin dikembangkan — hormati pilihannya."],
  },
  ENTJ: {
    nick: "Komandan", grup: "Analis", pct: 1.8,
    tagline: "Pemimpin tegas yang selalu menemukan (atau membuat) jalan.",
    desc: "ENTJ adalah pemimpin strategis paling alami di antara 16 tipe: visioner, tegas, dan sangat efisien menggerakkan orang dan sumber daya menuju target. Mereka berbicara langsung, berpikir besar, dan pantang menyerah pada hambatan.",
    fungsi: ["Te", "Ni", "Se", "Fi"],
    kekuatan: ["Visi strategis + eksekusi kuat", "Tegas dan percaya diri", "Efisien mengelola sumber daya", "Karisma kepemimpinan", "Tahan tekanan dan konflik", "Standar kinerja tinggi"],
    kelemahan: ["Dominan; bisa mengintimidasi", "Tidak sabar dan kurang toleran pada kelemahan", "Mengabaikan perasaan demi hasil", "Sulit menerima otoritas yang dianggap tidak kompeten", "Workaholic"],
    kerja: "Unggul memimpin perubahan dan pertumbuhan skala besar. Beri target ambisius dan wewenang penuh; pastikan ada rekan penyeimbang sisi manusia.",
    komunikasi: "Langsung, cepat, menantang. Bawakan argumen dengan percaya diri dan data — ia menghormati orang yang berani berdiri di posisinya.",
    karier: ["CEO / Eksekutif", "Konsultan Manajemen", "Pengacara Korporat", "Investment Banker", "Direktur Sales", "Entrepreneur Skala Besar", "Politisi Eksekutif", "COO / Direktur Operasional", "Manajer Program Besar", "Komisaris / Board Member"],
    tokoh: ["Steve Jobs", "Napoleon Bonaparte", "Sheryl Sandberg", "Gordon Ramsay"],
    tips: ["Kecepatan Anda bisa terasa seperti serangan — perlambat untuk membawa orang serta.", "Rayakan progres tim, bukan hanya menagih target berikutnya.", "Dengarkan sinyal emosi; itu juga data strategis."],
  },
};

// Ranking populasi (otomatis diurutkan dari data pct di atas)
function mbtiRanking() {
  return Object.entries(MBTI_TYPES)
    .map(([kode, v]) => ({ kode, nick: v.nick, grup: v.grup, pct: v.pct }))
    .sort((a, b) => b.pct - a.pct);
}
