// ═══════════════════════════════════════════════════════════════
// DATA TES LAIN — Big Five (50), DISC (28), RIASEC (36), EQ (20)
// r: true = item terbalik (reverse-scored)
// ═══════════════════════════════════════════════════════════════

// ── BIG FIVE / OCEAN — 10 item per dimensi ──
const BIG5_QUESTIONS = [
  // O — Keterbukaan
  { t: "Saya punya imajinasi yang hidup.", d: "O" },
  { t: "Saya senang mencoba hal-hal baru yang belum pernah saya lakukan.", d: "O" },
  { t: "Saya tertarik pada ide-ide abstrak dan filosofis.", d: "O" },
  { t: "Saya menikmati seni, musik, atau sastra secara mendalam.", d: "O" },
  { t: "Saya suka mempertanyakan cara lama dan mencari cara yang lebih baik.", d: "O" },
  { t: "Saya kesulitan memahami ide yang abstrak.", d: "O", r: true },
  { t: "Saya lebih suka rutinitas yang sudah saya kenal daripada perubahan.", d: "O", r: true },
  { t: "Saya tidak terlalu tertarik pada hal-hal berbau seni.", d: "O", r: true },
  { t: "Saya cepat memahami sudut pandang yang berbeda dari pandangan saya.", d: "O" },
  { t: "Rasa ingin tahu saya besar terhadap banyak bidang.", d: "O" },
  // C — Kesungguhan
  { t: "Saya selalu mempersiapkan segala sesuatunya dengan baik.", d: "C" },
  { t: "Saya memperhatikan detail dalam pekerjaan.", d: "C" },
  { t: "Saya menyelesaikan tugas sesuai rencana.", d: "C" },
  { t: "Saya menyukai keteraturan dan kerapian.", d: "C" },
  { t: "Saya menetapkan standar tinggi untuk diri sendiri dan berusaha memenuhinya.", d: "C" },
  { t: "Saya sering menunda pekerjaan penting.", d: "C", r: true },
  { t: "Saya sering meninggalkan barang tidak pada tempatnya.", d: "C", r: true },
  { t: "Saya mudah teralihkan dari tugas yang sedang saya kerjakan.", d: "C", r: true },
  { t: "Orang bisa mengandalkan saya untuk menepati janji.", d: "C" },
  { t: "Saya bekerja dengan tekun sampai pekerjaan benar-benar tuntas.", d: "C" },
  // E — Ekstraversi
  { t: "Saya nyaman menjadi pusat perhatian.", d: "E" },
  { t: "Saya mudah memulai percakapan dengan siapa saja.", d: "E" },
  { t: "Saya merasa nyaman berada di antara banyak orang.", d: "E" },
  { t: "Saya banyak bicara dalam kelompok.", d: "E" },
  { t: "Saya penuh energi dalam kegiatan sosial.", d: "E" },
  { t: "Saya tidak banyak bicara.", d: "E", r: true },
  { t: "Saya lebih suka berada di belakang layar.", d: "E", r: true },
  { t: "Saya menghindari keramaian bila memungkinkan.", d: "E", r: true },
  { t: "Saya mudah berteman di lingkungan baru.", d: "E" },
  { t: "Saya bersemangat mengajak orang melakukan kegiatan bersama.", d: "E" },
  // A — Keramahan
  { t: "Saya mudah bersimpati pada perasaan orang lain.", d: "A" },
  { t: "Saya meluangkan waktu untuk membantu orang lain.", d: "A" },
  { t: "Saya membuat orang lain merasa diterima.", d: "A" },
  { t: "Saya cenderung memercayai niat baik orang lain.", d: "A" },
  { t: "Saya lebih memilih bekerja sama daripada bersaing.", d: "A" },
  { t: "Saya tidak terlalu peduli dengan masalah orang lain.", d: "A", r: true },
  { t: "Saya kadang berkata tajam tanpa memikirkan perasaan orang.", d: "A", r: true },
  { t: "Saya sulit memaafkan orang yang pernah menyakiti saya.", d: "A", r: true },
  { t: "Saya memperlakukan semua orang dengan hormat dan hangat.", d: "A" },
  { t: "Saya senang membuat orang lain merasa nyaman.", d: "A" },
  // N — Neurotisisme
  { t: "Saya mudah merasa cemas.", d: "N" },
  { t: "Suasana hati saya mudah berubah-ubah.", d: "N" },
  { t: "Saya mudah tersinggung.", d: "N" },
  { t: "Saya sering mengkhawatirkan banyak hal.", d: "N" },
  { t: "Saya mudah merasa tertekan saat menghadapi masalah.", d: "N" },
  { t: "Saya jarang merasa sedih atau murung.", d: "N", r: true },
  { t: "Saya tetap tenang di bawah tekanan.", d: "N", r: true },
  { t: "Saya cepat pulih setelah kejadian yang mengecewakan.", d: "N", r: true },
  { t: "Saya sulit tidur karena memikirkan sesuatu.", d: "N" },
  { t: "Kritik kecil bisa mengganggu pikiran saya berhari-hari.", d: "N" },
];

const BIG5_TRAITS = {
  O: {
    nama: "Openness — Keterbukaan pada Pengalaman", warna: "#7c5cbf",
    apa: "Mengukur imajinasi, rasa ingin tahu intelektual, kepekaan estetika, dan keterbukaan pada ide serta cara baru.",
    tinggi: "Kreatif, imajinatif, senang belajar hal baru, nyaman dengan ambiguitas dan perubahan. Cocok untuk peran inovasi, strategi, riset, dan desain.",
    sedang: "Seimbang: terbuka pada ide baru bila ada alasan kuat, tetapi tetap menghargai cara yang sudah terbukti.",
    rendah: "Praktis, membumi, konsisten, dan menyukai hal yang konkret serta teruji. Kekuatan besar untuk peran operasional dan kepatuhan.",
    hr: "Prediktor kuat untuk keberhasilan pelatihan, adaptasi terhadap perubahan, dan peran kreatif/inovatif. Skor rendah bukan kelemahan — justru aset di pekerjaan yang menuntut konsistensi prosedur.",
  },
  C: {
    nama: "Conscientiousness — Kesungguhan", warna: "#3a7bd5",
    apa: "Mengukur disiplin diri, keteraturan, ketekunan, orientasi prestasi, dan rasa tanggung jawab.",
    tinggi: "Terorganisir, tekun, dapat diandalkan, dan berorientasi target. Menyelesaikan apa yang dimulai dengan standar tinggi.",
    sedang: "Cukup teratur dan bertanggung jawab, dengan fleksibilitas — tidak kaku pada rencana bila situasi berubah.",
    rendah: "Spontan, fleksibel, dan santai terhadap struktur; bekerja baik dalam mode improvisasi, namun perlu sistem eksternal untuk tenggat dan detail.",
    hr: "⭐ Prediktor kinerja kerja paling konsisten di hampir semua jenis pekerjaan (meta-analisis Barrick & Mount, 1991). Skor tinggi = indikator kuat keandalan, integritas kerja, dan pencapaian target.",
  },
  E: {
    nama: "Extraversion — Ekstraversi", warna: "#d5762a",
    apa: "Mengukur sumber energi sosial: asertivitas, antusiasme, kesenangan berinteraksi, dan dorongan mencari stimulasi.",
    tinggi: "Enerjik, asertif, mudah membangun jaringan, dan nyaman tampil. Cocok untuk sales, kepemimpinan publik, dan peran relasi.",
    sedang: "Ambivert: mampu tampil dan bersosialisasi saat dibutuhkan, tetapi juga produktif bekerja mandiri.",
    rendah: "Tenang, reflektif, mandiri, dan kuat dalam kerja mendalam (deep work). Mendengar lebih banyak daripada berbicara.",
    hr: "Prediktor baik untuk pekerjaan penjualan, kepemimpinan tim, dan peran yang menuntut interaksi intensif. Untuk peran analitis/teknis, skor rendah sering justru berkorelasi dengan fokus yang lebih baik.",
  },
  A: {
    nama: "Agreeableness — Keramahan", warna: "#2e9e6b",
    apa: "Mengukur kecenderungan kooperatif, empati, kepercayaan pada orang lain, dan orientasi menjaga hubungan.",
    tinggi: "Kooperatif, empatik, cinta damai, dan mudah dipercaya. Perekat tim dan andal di peran pelayanan.",
    sedang: "Mampu bekerja sama dengan baik, tetapi juga bisa tegas dan mengatakan 'tidak' bila diperlukan.",
    rendah: "Kompetitif, skeptis, dan tegas — tidak segan berkonfrontasi. Aset di negosiasi, penegakan aturan, dan keputusan sulit.",
    hr: "Penting untuk kerja tim, layanan pelanggan, dan peran keperawatan/pendidikan. Namun untuk peran negosiator atau pengambil keputusan sulit, skor sangat tinggi bisa menjadi hambatan (sulit menolak/menegur).",
  },
  N: {
    nama: "Neuroticism — Neurotisisme (kebalikan: Stabilitas Emosi)", warna: "#c74b62",
    apa: "Mengukur kecenderungan mengalami emosi negatif: cemas, mudah tersinggung, dan reaktif terhadap stres. Skor rendah = stabilitas emosi tinggi.",
    tinggi: "Sensitif dan waspada terhadap risiko — sering menjadi 'alarm dini' tim, tetapi rentan stres dan butuh lingkungan yang mendukung serta beban yang terkelola.",
    sedang: "Umumnya stabil dengan naik-turun emosi yang wajar; pulih dalam waktu normal setelah tekanan.",
    rendah: "Sangat tenang, tahan tekanan, dan tidak mudah goyah — aset besar untuk peran krisis, kepemimpinan, dan pekerjaan berisiko tinggi.",
    hr: "Stabilitas emosi (N rendah) adalah prediktor kinerja kedua terkuat setelah Conscientiousness, terutama untuk pekerjaan bertekanan tinggi. Kandidat N tinggi tetap bisa sangat sukses bila didukung manajemen stres dan lingkungan yang sehat.",
  },
};

// ── DISC — 28 item, 7 per gaya ──
const DISC_QUESTIONS = [
  { t: "Saya suka mengambil kendali dalam situasi kelompok.", d: "D" },
  { t: "Saya berorientasi pada hasil dan cepat mengambil keputusan.", d: "D" },
  { t: "Saya menikmati tantangan dan persaingan.", d: "D" },
  { t: "Saya langsung ke inti masalah tanpa banyak basa-basi.", d: "D" },
  { t: "Saya berani mengambil risiko untuk mencapai target.", d: "D" },
  { t: "Saya tidak sabar dengan proses yang berjalan lambat.", d: "D" },
  { t: "Saya nyaman membuat keputusan sulit yang tidak populer.", d: "D" },
  { t: "Saya mudah membuat orang lain antusias terhadap ide saya.", d: "I" },
  { t: "Saya senang bertemu orang baru dan membangun jaringan.", d: "I" },
  { t: "Saya orang yang optimis dan ekspresif.", d: "I" },
  { t: "Saya lebih suka suasana kerja yang menyenangkan dan hidup.", d: "I" },
  { t: "Saya persuasif dalam meyakinkan orang lain.", d: "I" },
  { t: "Saya suka bercerita dan menghibur orang.", d: "I" },
  { t: "Pengakuan dan apresiasi dari orang lain penting bagi saya.", d: "I" },
  { t: "Saya adalah pendengar yang sabar.", d: "S" },
  { t: "Saya setia dan konsisten kepada tim saya.", d: "S" },
  { t: "Saya lebih suka lingkungan kerja yang stabil dan dapat diprediksi.", d: "S" },
  { t: "Saya menghindari konflik bila memungkinkan.", d: "S" },
  { t: "Saya menyelesaikan pekerjaan dengan tempo yang tenang dan mantap.", d: "S" },
  { t: "Perubahan yang mendadak membuat saya tidak nyaman.", d: "S" },
  { t: "Saya mendahulukan kebutuhan tim daripada keinginan pribadi.", d: "S" },
  { t: "Saya memastikan pekerjaan akurat sebelum diserahkan.", d: "C" },
  { t: "Saya mengikuti prosedur dan standar dengan disiplin.", d: "C" },
  { t: "Saya menganalisis data terlebih dahulu sebelum mengambil keputusan.", d: "C" },
  { t: "Saya menetapkan standar kualitas yang tinggi.", d: "C" },
  { t: "Saya lebih suka bekerja dengan instruksi yang jelas dan rinci.", d: "C" },
  { t: "Saya tidak nyaman memutuskan sesuatu tanpa informasi yang lengkap.", d: "C" },
  { t: "Orang menilai saya teliti dan sistematis.", d: "C" },
];

const DISC_STYLES = {
  D: {
    nama: "Dominance — Dominan", warna: "#c74b4b", ikon: "🔥",
    inti: "Berorientasi hasil, tegas, cepat, dan menyukai tantangan serta kendali.",
    kekuatan: ["Pengambil keputusan cepat", "Berani menghadapi konflik & risiko", "Fokus kuat pada target", "Mandiri dan percaya diri", "Penggerak perubahan"],
    kelemahan: ["Bisa terkesan menekan atau kasar", "Kurang sabar mendengarkan", "Mengabaikan detail & prosedur", "Meremehkan perasaan orang"],
    motivasi: "Kendali, tantangan, hasil nyata, dan otoritas untuk memutuskan.",
    takut: "Dimanfaatkan, kehilangan kendali, atau dianggap lemah.",
    komunikasi: "Bicara singkat, langsung ke tujuan, fokus pada hasil. Jangan bertele-tele; berikan opsi, biarkan dia memutuskan.",
    karier: ["Eksekutif / Direktur", "Entrepreneur", "Manajer Proyek", "Sales Director", "Pengacara Litigasi", "Manajer Turnaround / Krisis"],
  },
  I: {
    nama: "Influence — Memengaruhi", warna: "#d5a53a", ikon: "🌟",
    inti: "Optimis, ekspresif, persuasif, dan berenergi tinggi dalam berinteraksi dengan orang.",
    kekuatan: ["Komunikator dan motivator alami", "Cepat membangun relasi & jaringan", "Antusias dan membawa energi positif", "Kreatif dan spontan", "Pandai memengaruhi tanpa memaksa"],
    kelemahan: ["Kurang memperhatikan detail", "Sulit menepati manajemen waktu", "Terlalu mengandalkan kesan & perasaan", "Menghindari percakapan yang tidak menyenangkan"],
    motivasi: "Pengakuan sosial, popularitas, suasana menyenangkan, dan kebebasan berekspresi.",
    takut: "Penolakan sosial, diabaikan, atau kehilangan pengaruh.",
    komunikasi: "Hangat dan penuh cerita. Beri waktu untuk ngobrol, tunjukkan antusiasme, dan bantu ia menuliskan komitmen agar tidak menguap.",
    karier: ["Marketing / Brand", "Public Relations", "Sales B2C", "Trainer / MC", "Content Creator", "Community / Event Manager"],
  },
  S: {
    nama: "Steadiness — Stabil", warna: "#2e9e6b", ikon: "🌿",
    inti: "Sabar, konsisten, kooperatif, dan menjadi penstabil tim yang dapat diandalkan.",
    kekuatan: ["Pendengar dan penengah yang baik", "Sangat loyal dan konsisten", "Sabar menghadapi proses & orang", "Pemain tim sejati", "Tenang dan menenangkan"],
    kelemahan: ["Sulit berkata 'tidak'", "Resisten terhadap perubahan mendadak", "Terlalu menghindari konflik", "Kurang menyuarakan pendapat sendiri"],
    motivasi: "Stabilitas, keamanan, apresiasi yang tulus, dan hubungan jangka panjang.",
    takut: "Perubahan mendadak, konflik terbuka, dan kehilangan rasa aman.",
    komunikasi: "Lembut dan pribadi. Beri konteks dan waktu adaptasi saat ada perubahan; tanyakan pendapatnya secara langsung karena ia jarang menyela.",
    karier: ["HR / General Affairs", "Perawat / Caregiver", "Customer Support", "Administrasi", "Guru", "Manajer Operasional Tim Kecil"],
  },
  C: {
    nama: "Conscientiousness — Teliti", warna: "#3a7bd5", ikon: "📐",
    inti: "Analitis, akurat, sistematis, dan berpegang pada standar kualitas serta prosedur.",
    kekuatan: ["Ketelitian dan akurasi tinggi", "Berpikir analitis dan objektif", "Menjaga standar & kepatuhan", "Perencana yang sistematis", "Diplomatis dan hati-hati"],
    kelemahan: ["Perfeksionis; lambat memutuskan", "Terlalu kritis pada diri & orang lain", "Kaku pada prosedur", "Menjaga jarak secara emosional"],
    motivasi: "Kualitas, akurasi, keahlian, dan waktu yang cukup untuk bekerja dengan benar.",
    takut: "Dikritik atas kesalahan, situasi kacau tanpa standar, dan keputusan gegabah.",
    komunikasi: "Berbasis data dan tertulis. Siapkan fakta dan detail; beri waktu menganalisis; jangan memaksa keputusan instan.",
    karier: ["Akuntan / Auditor", "Quality Assurance", "Analis Data / Riset", "Insinyur", "Legal / Compliance", "Programmer"],
  },
};

// Nama kombinasi gaya utama + sekunder
const DISC_COMBO = {
  DI: "Penggerak Persuasif — memimpin dengan energi dan karisma, cepat sekaligus menular semangatnya.",
  DC: "Eksekutor Presisi — tegas pada target sekaligus menuntut kualitas; standar ganda yang kuat.",
  DS: "Pemimpin Tenang — tegas mengambil keputusan namun stabil dan tidak meledak-ledak.",
  ID: "Motivator Enerjik — memengaruhi orang dengan antusiasme dan keberanian mengambil inisiatif.",
  IS: "Perangkul Tim — hangat, suportif, dan membuat semua orang merasa dilibatkan.",
  IC: "Komunikator Teliti — persuasif namun tetap berpegang pada fakta dan ketepatan.",
  SD: "Pelaksana Tangguh — konsisten dan sabar, dengan ketegasan tersembunyi saat dibutuhkan.",
  SI: "Pendukung Hangat — penstabil tim yang ramah dan mudah didekati.",
  SC: "Penjaga Stabilitas — teliti, konsisten, dan sangat dapat diandalkan untuk jangka panjang.",
  CD: "Analis Tegas — perfeksionis yang berani menuntut standar dan mengambil keputusan sulit.",
  CI: "Penilai Komunikatif — analitis namun mampu menyampaikan temuan dengan cara yang enak didengar.",
  CS: "Spesialis Metodis — akurat, sabar, dan tekun; tulang punggung kualitas organisasi.",
};

// ── RIASEC / HOLLAND — 36 item, 6 per tipe ──
const RIASEC_QUESTIONS = [
  { t: "Memperbaiki peralatan elektronik atau mesin.", d: "R" },
  { t: "Bekerja menggunakan perkakas dan alat teknik.", d: "R" },
  { t: "Merakit atau membangun sesuatu dengan tangan.", d: "R" },
  { t: "Bekerja di luar ruangan (lapangan, alam).", d: "R" },
  { t: "Mengoperasikan kendaraan atau alat berat.", d: "R" },
  { t: "Pekerjaan fisik yang terlihat hasilnya secara nyata.", d: "R" },
  { t: "Memecahkan soal matematika atau teka-teki logika.", d: "I" },
  { t: "Melakukan eksperimen atau penelitian.", d: "I" },
  { t: "Membaca artikel atau jurnal ilmiah.", d: "I" },
  { t: "Menganalisis data untuk menemukan pola.", d: "I" },
  { t: "Menyelidiki akar penyebab suatu masalah.", d: "I" },
  { t: "Mempelajari teori atau konsep baru secara mendalam.", d: "I" },
  { t: "Menggambar, melukis, atau mendesain.", d: "A" },
  { t: "Menulis cerita, puisi, atau artikel.", d: "A" },
  { t: "Bermain musik atau menciptakan lagu.", d: "A" },
  { t: "Fotografi atau membuat video.", d: "A" },
  { t: "Merancang tampilan visual (layout, dekorasi, fashion).", d: "A" },
  { t: "Tampil di atas panggung (menyanyi, akting, menari).", d: "A" },
  { t: "Mengajari orang lain suatu keterampilan.", d: "S" },
  { t: "Mendengarkan dan membantu orang yang punya masalah.", d: "S" },
  { t: "Merawat orang sakit atau lansia.", d: "S" },
  { t: "Mengikuti kegiatan sukarela / sosial.", d: "S" },
  { t: "Melatih atau membimbing pengembangan orang lain.", d: "S" },
  { t: "Melayani dan membantu pelanggan.", d: "S" },
  { t: "Memimpin sebuah proyek atau tim.", d: "E" },
  { t: "Menjual produk atau meyakinkan orang tentang suatu ide.", d: "E" },
  { t: "Bernegosiasi untuk mendapatkan kesepakatan terbaik.", d: "E" },
  { t: "Memulai dan mengembangkan usaha sendiri.", d: "E" },
  { t: "Berpidato atau presentasi di depan banyak orang.", d: "E" },
  { t: "Memengaruhi keputusan penting dalam organisasi.", d: "E" },
  { t: "Menyusun data ke dalam spreadsheet dengan rapi.", d: "K" },
  { t: "Mengelola arsip dan dokumen secara sistematis.", d: "K" },
  { t: "Membuat laporan keuangan atau pembukuan.", d: "K" },
  { t: "Memeriksa dokumen untuk menemukan kesalahan kecil.", d: "K" },
  { t: "Bekerja mengikuti prosedur yang jelas dan pasti.", d: "K" },
  { t: "Mengelola jadwal, administrasi, dan hal-hal detail.", d: "K" },
];

const RIASEC_TYPES = {
  R: { nama: "Realistic — Realistis (Doers)", warna: "#8a6d3b", ikon: "🔧",
    desc: "Menyukai pekerjaan praktis dan konkret: alat, mesin, fisik, dan hasil nyata. Kuat dalam keterampilan teknis.",
    karier: ["Insinyur Mesin/Sipil", "Teknisi", "Pilot", "Arsitek Lapangan", "Petani Modern / Agribisnis", "Montir", "Elektrisi", "Operator Produksi"] },
  I: { nama: "Investigative — Investigatif (Thinkers)", warna: "#7c5cbf", ikon: "🔬",
    desc: "Menyukai analisis, riset, dan pemecahan masalah intelektual. Kuat dalam logika, sains, dan data.",
    karier: ["Peneliti / Ilmuwan", "Data Scientist", "Dokter", "Apoteker", "Analis Keuangan", "Programmer", "Laboran", "Ekonom"] },
  A: { nama: "Artistic — Artistik (Creators)", warna: "#c74b8a",  ikon: "🎨",
    desc: "Menyukai ekspresi kreatif, estetika, dan kebebasan dari struktur kaku. Kuat dalam ide orisinal dan rasa seni.",
    karier: ["Desainer Grafis/UX", "Penulis / Editor", "Musisi", "Fotografer", "Arsitek Desain", "Animator", "Copywriter", "Fashion Designer"] },
  S: { nama: "Social — Sosial (Helpers)", warna: "#2e9e6b", ikon: "🤝",
    desc: "Menyukai membantu, mengajar, dan mengembangkan orang. Kuat dalam empati, komunikasi, dan pelayanan.",
    karier: ["Guru / Dosen", "Perawat / Bidan", "Psikolog / Konselor", "HRD", "Pekerja Sosial", "Fisioterapis", "Customer Success", "Trainer"] },
  E: { nama: "Enterprising — Wirausaha (Persuaders)", warna: "#d5762a", ikon: "🚀",
    desc: "Menyukai memimpin, memengaruhi, dan mengejar target bisnis. Kuat dalam persuasi, keberanian, dan ambisi.",
    karier: ["Entrepreneur", "Manajer / Eksekutif", "Sales & BD", "Pengacara", "Marketing Manager", "Politisi", "Real Estate", "Konsultan Bisnis"] },
  K: { nama: "Conventional — Konvensional (Organizers)", warna: "#3a7bd5", ikon: "📋",
    desc: "Menyukai keteraturan, data, dan sistem administratif yang jelas. Kuat dalam ketelitian dan keandalan proses.",
    karier: ["Akuntan", "Auditor", "Admin / Sekretaris", "Analis Anggaran", "Staf Bank", "Manajer Kantor", "Staf Pajak", "Data Entry Specialist"] },
};

// ── EQ — 20 item, 5 per domain (model Goleman/Bradberry) ──
const EQ_QUESTIONS = [
  { t: "Saya menyadari emosi saya pada saat emosi itu muncul.", d: "SA" },
  { t: "Saya tahu situasi apa saja yang menjadi pemicu stres saya.", d: "SA" },
  { t: "Saya bisa menamai perasaan saya dengan tepat (bukan sekadar 'baik/buruk').", d: "SA" },
  { t: "Saya memahami bagaimana emosi memengaruhi keputusan saya.", d: "SA" },
  { t: "Saya terbuka menerima umpan balik tentang diri saya.", d: "SA" },
  { t: "Saya tetap tenang ketika dikritik.", d: "SM" },
  { t: "Saya mampu menahan reaksi impulsif saat marah.", d: "SM" },
  { t: "Saya cepat bangkit setelah mengalami kegagalan.", d: "SM" },
  { t: "Saya bisa memotivasi diri sendiri tanpa dorongan dari luar.", d: "SM" },
  { t: "Saya tetap menepati komitmen meski suasana hati sedang buruk.", d: "SM" },
  { t: "Saya cepat menangkap perasaan orang dari nada bicara dan bahasa tubuhnya.", d: "SO" },
  { t: "Saya menyesuaikan gaya komunikasi dengan lawan bicara.", d: "SO" },
  { t: "Saya memperhatikan dinamika yang terjadi dalam kelompok.", d: "SO" },
  { t: "Orang merasa dipahami ketika bercerita kepada saya.", d: "SO" },
  { t: "Saya peka terhadap kebutuhan orang yang tidak diucapkan.", d: "SO" },
  { t: "Saya bisa menyampaikan hal sulit tanpa merusak hubungan.", d: "RM" },
  { t: "Saya mampu menengahi konflik antara orang lain.", d: "RM" },
  { t: "Saya mudah membangun kepercayaan dengan orang baru.", d: "RM" },
  { t: "Saya memberi apresiasi kepada orang lain secara spesifik.", d: "RM" },
  { t: "Saya mampu memengaruhi orang lain secara positif.", d: "RM" },
];

const EQ_DOMAINS = {
  SA: { nama: "Self-Awareness — Kesadaran Diri", warna: "#7c5cbf", ikon: "🪞",
    desc: "Mengenali emosi sendiri dan dampaknya. Fondasi dari seluruh kecerdasan emosional.",
    tips: "Latih dengan jurnal emosi harian: catat 1 emosi + pemicunya + reaksi Anda setiap hari selama 2 minggu." },
  SM: { nama: "Self-Management — Pengelolaan Diri", warna: "#3a7bd5", ikon: "🧘",
    desc: "Mengelola reaksi emosional, menahan impuls, dan tetap produktif di bawah tekanan.",
    tips: "Terapkan 'jeda 6 detik' sebelum merespons pesan/situasi yang memancing emosi; amigdala butuh waktu itu untuk mereda." },
  SO: { nama: "Social Awareness — Kesadaran Sosial", warna: "#2e9e6b", ikon: "👁️",
    desc: "Membaca emosi orang lain dan dinamika kelompok — termasuk yang tidak diucapkan.",
    tips: "Dalam 3 rapat berikutnya, amati dulu: siapa yang diam, siapa yang tegang, apa yang tidak dikatakan — sebelum Anda bicara." },
  RM: { nama: "Relationship Management — Pengelolaan Hubungan", warna: "#d5762a", ikon: "🤝",
    desc: "Menggunakan kesadaran emosi untuk membangun kepercayaan, memengaruhi, dan mengelola konflik.",
    tips: "Beri 1 apresiasi spesifik per hari kepada orang berbeda ('presentasimu bagian X membantu saya karena Y') — bukan pujian generik." },
};
